repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        exclude: \.(min\.css|min\.js|po|mo)$
      - id: end-of-file-fixer
        exclude: \.(min\.css|min\.js|po|mo)$
      - id: mixed-line-ending
        args: [ '--fix=lf' ]
      - id: fix-encoding-pragma
        args: [ '--remove' ]

  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        language_version: python3.8

  - repo: https://gitlab.com/pycqa/flake8
    rev: '3.9.2'
    hooks:
      - id: flake8
